---FUNCION QUE FALTABA
CREATE OR REPLACE FUNCTION FIDE_PERSONA_TB_VALIDAR_NOMBRE_USUARIO_FN(P_NOMBRE_USUARIO VARCHAR)
RETURN NUMBER IS
P_RESULTADO NUMBER;
BEGIN
    SELECT COUNT(*) INTO P_RESULTADO
    FROM FIDE_PERSONA_TB WHERE NOMBRE_USUARIO = P_NOMBRE_USUARIO 
    AND ID_ESTADO = 1;
    RETURN P_RESULTADO;
END;
------------------------------------
--CREACION DE LOS PROCEDIMIENTOS, INSERTS
CREATE OR REPLACE PROCEDURE FIDE_ANANLISIS_VENTA_TB_INSERTAR_DATOS_SP(
    P_TOTAL_VENTAS IN NUMBER,
    P_FRECUENCIA IN NUMBER,
    P_ID_PRODUCTO IN NUMBER,
    P_ID_PERSONA IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_ANALISIS_VENTA_TB
    (TOTAL_VENTAS,FRECUENCIA,ID_PRODUCTO,ID_PERSONA)
    VALUES(P_TOTAL_VENTAS,P_FRECUENCIA,P_ID_PRODUCTO,P_ID_PERSONA);
    COMMIT;
END FIDE_ANANLISIS_VENTA_TB_INSERTAR_DATOS_SP;

/
CREATE OR REPLACE PROCEDURE FIDE_CANTON_TB_INSERTAR_DATOS_SP(
    P_NOMBRE IN VARCHAR2
)AS
BEGIN
    INSERT INTO FIDE_CANTON_TB(NOMBRE)
    VALUES(P_NOMBRE);
    COMMIT;
END FIDE_CANTON_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_CATEGORIA_TB_INSERTAR_DATOS_SP(
    P_NOMBRE_CATEGORIA IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
)AS
BEGIN
    INSERT INTO FIDE_CATEGORIA_TB(NOMBRE_CATEGORIA,DESCRIPCION)
    VALUES(P_NOMBRE_CATEGORIA,P_DESCRIPCION);
    COMMIT;
END FIDE_CATEGORIA_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_DEVOLUCION_TB_INSERTAR_DATOS_SP(
    P_RAZON IN VARCHAR2,
    P_FECHA_DEVOLUCION IN DATE,
    P_ID_PRODUCTO IN NUMBER,
    P_ID_FACTURA_HEADER IN NUMBER,
    P_ID_INVENTARIO IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_DEVOLUCION_TB(RAZON,FECHA_DEVOLUCION,ID_PRODUCTO,ID_FACTURA_HEADER,ID_INVENTARIO)
    VALUES(P_RAZON,P_FECHA_DEVOLUCION,P_ID_PRODUCTO,P_ID_FACTURA_HEADER,P_ID_INVENTARIO);
    COMMIT;
END FIDE_DEVOLUCION_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_DIRECCION_TB_INSERTAR_DATOS_SP(
    P_DETALLE IN VARCHAR2,
    P_ID_PAIS IN NUMBER,
    P_ID_PROVINCIA IN NUMBER,
    P_ID_CANTON IN NUMBER,
    P_ID_DISTRITO IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_DIRECCION_TB(DETALLE,ID_PAIS,ID_PROVINCIA,ID_CANTON,ID_DISTRITO)
    VALUES(P_DETALLE,P_ID_PAIS,P_ID_PROVINCIA,P_ID_CANTON,P_ID_DISTRITO);
    COMMIT;
END FIDE_DIRECCION_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_DISTRITO_TB_INSERTAR_DATOS_SP(
    P_NOMBRE IN VARCHAR2
)AS
BEGIN
    INSERT INTO FIDE_DISTRITO_TB(NOMBRE)
    VALUES(P_NOMBRE);
    COMMIT;
END FIDE_DISTRITO_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_ESTADO_TB_INSERTAR_DATOS_SP(
    P_ID_ESTADO IN NUMBER,
    P_DESCRIPCION IN VARCHAR2
)AS
BEGIN
    INSERT INTO FIDE_ESTADO_TB(ID_ESTADO,DESCRIPCION)
    VALUES(P_ID_ESTADO,P_DESCRIPCION);
    COMMIT;
END FIDE_ESTADO_TB_INSERTAR_DATOS_SP;

/
CREATE OR REPLACE PROCEDURE FIDE_FACTURA_DETALLE_TB_INSERTAR_DATOS_SP(
    P_PRECIO IN NUMBER,
    P_CANTIDAD IN NUMBER,
    P_ID_PRODUCTO IN NUMBER,
    P_ID_FACTURA_HEADER IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_FACTURA_DETALLE_TB(PRECIO,CANTIDAD,ID_PRODUCTO,ID_FACTURA_HEADER)
    VALUES(P_PRECIO,P_CANTIDAD,P_ID_PRODUCTO,P_ID_FACTURA_HEADER);
    COMMIT;
END FIDE_FACTURA_DETALLE_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_FACTURA_HEADER_TB_INSERTAR_DATOS_SP(
    P_FECHA_FACTURA IN DATE,
    P_SUBTOTAL IN NUMBER,
    P_IMPUESTO IN NUMBER,
    P_TOTAL IN NUMBER,
    P_TOTAL_LINEAS IN NUMBER,
    P_ID_METODO_PAGO IN NUMBER,
    P_ID_PERSONA IN NUMBER,
    P_ID_SUCURSAL IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_FACTURA_HEADER_TB
    (FECHA_FACTURA,SUBTOTAL,IMPUESTO,TOTAL,TOTAL_LINEAS,ID_METODO_PAGO,ID_PERSONA,ID_SUCURSAL)
    VALUES(P_FECHA_FACTURA,P_SUBTOTAL,P_IMPUESTO,P_TOTAL,P_TOTAL_LINEAS,P_ID_METODO_PAGO,P_ID_PERSONA,P_ID_SUCURSAL);
    COMMIT;
END FIDE_FACTURA_HEADER_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_INVENTARIO_TB_INSERTAR_DATOS_SP(
    P_CANTIDAD IN NUMBER,
    P_ID_PRODUCTO IN NUMBER,
    P_ID_SUCURSAL IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_INVENTARIO_TB(CANTIDAD,ID_PRODUCTO,ID_SUCURSAL)
    VALUES(P_CANTIDAD,P_ID_PRODUCTO,P_ID_SUCURSAL);
    COMMIT;
END FIDE_INVENTARIO_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_METODO_PAGO_TB_INSERTAR_DATOS_SP(
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
)AS
BEGIN
    INSERT INTO FIDE_METODO_PAGO_TB(NOMBRE,DESCRIPCION)
    VALUES(P_NOMBRE,P_DESCRIPCION);
    COMMIT;
END FIDE_METODO_PAGO_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_PAIS_TB_INSERTAR_DATOS_SP(
    P_NOMBRE IN VARCHAR2
)AS
BEGIN
    INSERT INTO FIDE_PAIS_TB(NOMBRE)
    VALUES(P_NOMBRE);
    COMMIT;
END FIDE_PAIS_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_PEDIDO_TB_INSERTAR_DATOS_SP(
    P_FECHA_PEDIDO IN DATE,
    P_ID_PROVEEDOR IN NUMBER,
    P_ID_PERSONA IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_PEDIDO_TB(FECHA_PEDIDO,ID_PROVEEDOR,ID_PERSONA)
    VALUES(P_FECHA_PEDIDO,P_ID_PROVEEDOR,P_ID_PERSONA);
    COMMIT;
END FIDE_PEDIDO_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_PERSONA_TB_INSERTAR_DATOS_SP(
    P_NOMBRE IN VARCHAR2,
    P_APELLIDO1 IN VARCHAR2,
    P_APELLIDO2 IN VARCHAR2,
    P_CORREO IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_NOMBRE_USUARIO IN VARCHAR2,
    P_CONTRASENA IN VARCHAR2,
    P_ID_DIRECCION IN NUMBER,
    P_ID_ROL IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_PERSONA_TB
    (NOMBRE,APELLIDO1,APELLIDO2,CORREO,TELEFONO,NOMBRE_USUARIO,CONTRASENA,ID_DIRECCION,ID_ROL)
    VALUES(P_NOMBRE,P_APELLIDO1,P_APELLIDO2,P_CORREO,P_TELEFONO,P_NOMBRE_USUARIO,P_CONTRASENA,P_ID_DIRECCION,P_ID_ROL);
    COMMIT;
END FIDE_PERSONA_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_PRODUCTO_TB_INSERTAR_DATOS_SP(
    P_NOMBRE_PRODUCTO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2,
    P_PRECIO_UNITARIO IN NUMBER,
    P_FECHA_VENCIMIENTO IN DATE,
    P_ID_CATEGORIA IN NUMBER,
    P_ID_PROVEEDOR IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_PRODUCTO_TB
    (NOMBRE_PRODUCTO,DESCRIPCION,PRECIO_UNITARIO,FECHA_VENCIMIENTO,ID_CATEGORIA,ID_PROVEEDOR)
    VALUES(P_NOMBRE_PRODUCTO,P_DESCRIPCION,P_PRECIO_UNITARIO,P_FECHA_VENCIMIENTO,P_ID_CATEGORIA,P_ID_PROVEEDOR);
    COMMIT;
END FIDE_PRODUCTO_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_PROMOCION_TB_INSERTAR_DATOS_SP(
    P_DESCRIPCION IN VARCHAR2,
    P_FECHA_INICIO IN DATE,
    P_FECHA_FIN IN DATE,
    P_DESCUENTO IN NUMBER,
    P_ID_PRODUCTO IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_PROMOCION_TB
    (DESCRIPCION,FECHA_INICIO,FECHA_FIN,DESCUENTO,ID_PRODUCTO)
    VALUES(P_DESCRIPCION,P_FECHA_INICIO,P_FECHA_FIN,P_DESCUENTO,P_ID_PRODUCTO);
    COMMIT;
END FIDE_PROMOCION_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_PROVEEDOR_TB_INSERTAR_DATOS_SP(
    P_NOMBRE_PROVEEDOR IN VARCHAR2,
    P_APELLIDO1 IN VARCHAR2,
    P_APELLIDO2 IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_ID_DIRECCION IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_PROVEEDOR_TB
    (NOMBRE_PROVEEDOR,APELLIDO1,APELLIDO2,TELEFONO,ID_DIRECCION)
    VALUES(P_NOMBRE_PROVEEDOR,P_APELLIDO1,P_APELLIDO2,P_TELEFONO,P_ID_DIRECCION);
    COMMIT;
END FIDE_PROVEEDOR_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_PROVINCIA_TB_INSERTAR_DATOS_SP(
    P_NOMBRE IN VARCHAR2
)AS
BEGIN
    INSERT INTO FIDE_PROVINCIA_TB(NOMBRE)VALUES(P_NOMBRE);
    COMMIT;
END FIDE_PROVINCIA_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_ROL_TB_INSERTAR_DATOS_SP(
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
)AS
BEGIN
    INSERT INTO FIDE_ROL_TB(NOMBRE,DESCRIPCION)VALUES(P_NOMBRE,P_DESCRIPCION);
    COMMIT;
END FIDE_ROL_TB_INSERTAR_DATOS_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_SUCURSAL_TB_INSERTAR_DATOS_SP(
    P_NOMBRE IN VARCHAR2,
    P_ID_DIRECCION IN NUMBER
)AS
BEGIN
    INSERT INTO FIDE_SUCURSAL_TB(NOMBRE,ID_DIRECCION)VALUES(P_NOMBRE,P_ID_DIRECCION);
    COMMIT;
END FIDE_SUCURSAL_TB_INSERTAR_DATOS_SP;


---------------------------------------------
--PROCEDIMIENTOS PARA VER 1 REGISTRO

CREATE OR REPLACE PROCEDURE FIDE_CATEGORIA_TB_VER_DATOS_SP(
    P_ID_CATEGORIA IN NUMBER,
    P_NOMBRE_CATEGORIA OUT VARCHAR2,
    P_DESCRIPCION OUT VARCHAR2
)AS
BEGIN
    SELECT NOMBRE_CATEGORIA,DESCRIPCION 
    INTO P_NOMBRE_CATEGORIA,P_DESCRIPCION
    FROM FIDE_CATEGORIA_TB 
    WHERE ID_CATEGORIA=P_ID_CATEGORIA;
END FIDE_CATEGORIA_TB_VER_DATOS_SP;

-----------------------------------------------

---DUDA AQUI
--MODIFICAR SOLAMENTE LOS DATOS DE CATEGORIA
CREATE OR REPLACE PROCEDURE FIDE_CATEGORIA_TB_MODIFICAR_DATOS_SP(
    P_ID_CATEGORIRA IN NUMBER,
    P_NOMBRE_CATEGORIA IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
)AS
BEGIN
    UPDATE FIDE_CATEGORIA_TB
    SET NOMBRE_CATEGORIA=P_NOMBRE_CATEGORIA,
    DESCRIPCION = P_DESCRIPCION
    WHERE ID_CATEGORIA = P_ID_CATEGORIRA;
    COMMIT;
END FIDE_CATEGORIA_TB_MODIFICAR_DATOS_SP;

---PROCEDIMIENTO PARA DESACTIVAR UN REGISTRO
CREATE OR REPLACE PROCEDURE FIDE_CATEGORIA_TB_DESACTIVAR_DATOS_SP(
    P_ID_CATEGORIRA IN NUMBER
)AS
BEGIN
    UPDATE FIDE_CATEGORIA_TB
    --2 PORQUE 1 ES ACTIVO Y 2 INACTIVO
    SET ID_ESTADO = 2 
    WHERE ID_CATEGORIA = P_ID_CATEGORIRA;
    COMMIT;
END FIDE_CATEGORIA_TB_DESACTIVAR_DATOS_SP;


--PROCEDIMIENTO PARA MODIFICAR DATOS Y TAMBIEN PODER DESACTIVAR UN REGISTRO
CREATE OR REPLACE PROCEDURE FIDE_CATEGORIA_TB_MODIFICAR_DATOS2_SP(
    P_ID_CATEGORIRA IN NUMBER,
    P_NOMBRE_CATEGORIA IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2,
    P_ID_ESTADO IN VARCHAR2
)AS
BEGIN
    UPDATE FIDE_CATEGORIA_TB
    SET NOMBRE_CATEGORIA=P_NOMBRE_CATEGORIA,
    DESCRIPCION = P_DESCRIPCION,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_CATEGORIA = P_ID_CATEGORIRA;
    COMMIT;
END FIDE_CATEGORIA_TB_MODIFICAR_DATOS2_SP;




-----
----PROCEDIMIENTO PARA EL INICIO DE SESSION
CREATE OR REPLACE PROCEDURE FIDE_PERSONA_TB_OBTENER_USUARIO_SP(
    P_NOMBRE_USUARIO IN VARCHAR2,
    P_ID_PERSONA OUT NUMBER,
    P_CONTRASENA OUT VARCHAR2,
    P_ID_ROL OUT NUMBER
)AS
BEGIN
    SELECT ID_PERSONA, CONTRASENA, ID_ROL 
    INTO P_ID_PERSONA, P_CONTRASENA,P_ID_ROL
    FROM FIDE_PERSONA_TB 
    WHERE NOMBRE_USUARIO = P_NOMBRE_USUARIO
    AND ID_ESTADO = 1;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_ID_PERSONA:= NULL;
        P_CONTRASENA:= NULL;
        P_ID_ROL:= NULL;
END FIDE_PERSONA_TB_OBTENER_USUARIO_SP;
