--CREACION DE SECUENCIAS

CREATE SEQUENCE ID_ANALISIS_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_CANTON_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_CATEGORIA_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_DEVOLUCION_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ID_DIRECCION_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_DISTRITO_SEQ
START WITH 1
INCREMENT BY 1;
/
--NO SE CREA PORQUE SOLO VAN A VER 2
--CREATE SEQUENCE ID_ESTADO_SEQ
--START WITH 1
--INCREMENT BY 1;

CREATE SEQUENCE ID_FACTURA_DETALLE_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_FACTURA_HEADER_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_INVENTARIO_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_METODO_PAGO_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_PAIS_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_PEDIDO_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_PERSONA_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_PRODUCTO_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_PROMOCION_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_PROVEEDOR_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_PROVINCIA_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_ROL_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE ID_SUCURSAL_SEQ
START WITH 1
INCREMENT BY 1;

--------------------------------

--CREACION DE LOS TRIGGERS PARA EL ID
CREATE OR REPLACE TRIGGER FIDE_ANALISIS_VENTA_TB_ID_ANALISIS_TRG
BEFORE INSERT ON FIDE_ANALISIS_VENTA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ANALISIS:=ID_ANALISIS_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_ID_CANTON_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.ID_CANTON:=ID_CANTON_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TB_ID_CATEGORIA_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_CATEGORIA := ID_CATEGORIA_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DEVOLUCION_TB_ID_DEVOLUCION_TRG
BEFORE INSERT ON FIDE_DEVOLUCION_TB
FOR EACH ROW
BEGIN
    :NEW.ID_DEVOLUCION := ID_DEVOLUCION_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_ID_DIRECCION_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.ID_DIRECCION := ID_DIRECCION_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_ID_DISTRITO_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_DISTRITO := ID_DISTRITO_SEQ.NEXTVAL;
END;
/
   
CREATE OR REPLACE TRIGGER FIDE_FACTURA_DETALLE_TB_ID_FACTURA_DETALLE_TRG
BEFORE INSERT ON FIDE_FACTURA_DETALLE_TB
FOR EACH ROW
BEGIN
    :NEW.ID_FACTURA_DETALLE := ID_FACTURA_DETALLE_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_HEADER_TB_ID_FACTURA_HEADER_TRG
BEFORE INSERT ON FIDE_FACTURA_HEADER_TB
FOR EACH ROW
BEGIN
    :NEW.ID_FACTURA_HEADER := ID_FACTURA_HEADER_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_ID_INVENTARIO_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
   :NEW.ID_INVENTARIO := ID_INVENTARIO_SEQ.NEXTVAL;
END;
/
   
CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_ID_METODO_PAGO_TRG
BEFORE INSERT ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
   :NEW.ID_METODO_PAGO := ID_METODO_PAGO_SEQ.NEXTVAL;
END;
/
   
CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_ID_PAIS_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
   :NEW.ID_PAIS := ID_PAIS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PEDIDO_TB_ID_PEDIDO_TRG
BEFORE INSERT ON FIDE_PEDIDO_TB
FOR EACH ROW
BEGIN
   :NEW.ID_PEDIDO := ID_PEDIDO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PERSONA_TB_ID_PERSONA_TRG
BEFORE INSERT ON FIDE_PERSONA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_PERSONA:=ID_PERSONA_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_ID_PRODUCTO_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
   :NEW.ID_PRODUCTO := ID_PRODUCTO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROMOCION_TB_ID_PROMOCION_TRG
BEFORE INSERT ON FIDE_PROMOCION_TB
FOR EACH ROW
BEGIN
   :NEW.ID_PROMOCION := ID_PROMOCION_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_ID_PROVEEDOR_TRG
BEFORE INSERT ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
   :NEW.ID_PROVEEDOR := ID_PROVEEDOR_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_ID_PROVINCIA_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
   :NEW.ID_PROVINCIA := ID_PROVINCIA_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ROL_TB_ID_ROL_TRG
BEFORE INSERT ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
   :NEW.ID_ROL := ID_ROL_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_SUCURSAL_TB_ID_SUCURSAL_TRG
BEFORE INSERT ON FIDE_SUCURSAL_TB
FOR EACH ROW
BEGIN
   :NEW.ID_SUCURSAL := ID_SUCURSAL_SEQ.NEXTVAL;
END;
/

-----------------------------------------------------------
--CREACION DE TRIGERS PARA EL CREADO_POR, FECHA_CREACION,
--MODIFICADO_POR, FECHA_MODIFICACION, ACCION, ID_ESTADO

--TRIGGERS PARA VER LA FECHA DE INSERCION O MODIFICACION
CREATE OR REPLACE TRIGGER FIDE_ANALISIS_VENTA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ANALISIS_VENTA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DEVOLUCION_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DEVOLUCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_DETALLE_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_DETALLE_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_HEADER_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_HEADER_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PEDIDO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PERSONA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PERSONA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROMOCION_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROMOCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ROL_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_SUCURSAL_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_SUCURSAL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

--TRIGGER PARA VER QUIEN INSERTO O MODIFICO
CREATE OR REPLACE TRIGGER FIDE_ANALISIS_VENTA_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ANALISIS_VENTA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.CREADO_POR:=USER;
ELSE
    :NEW.MODIFICADO_POR:=USER;
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_DEVOLUCION_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DEVOLUCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_DETALLE_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_DETALLE_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_FACTURA_HEADER_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_HEADER_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PEDIDO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PERSONA_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PERSONA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PROMOCION_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROMOCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_ROL_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_SUCURSAL_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_SUCURSAL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/ 

-----
--TRIGGER PARA VER LA ACCION

CREATE OR REPLACE TRIGGER FIDE_ANALISIS_VENTA_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ANALISIS_VENTA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DEVOLUCION_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DEVOLUCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_DETALLE_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_DETALLE_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_FACTURA_HEADER_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_HEADER_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PEDIDO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PEDIDO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PERSONA_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PERSONA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PROMOCION_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROMOCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ROL_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SUCURSAL_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_SUCURSAL_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

---
--TRIGGER PARA EL ESTADO
CREATE OR REPLACE TRIGGER FIDE_ANALISIS_VENTA_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_ANALISIS_VENTA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_DEVOLUCION_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_DEVOLUCION_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_FACTURA_DETALLE_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_FACTURA_DETALLE_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_FACTURA_HEADER_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_FACTURA_HEADER_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PEDIDO_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PEDIDO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PERSONA_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PERSONA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PROMOCION_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PROMOCION_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_ROL_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_SUCURSAL_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_SUCURSAL_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 1;
END;
/ 

SELECT COUNT(TRIGGER_NAME)
FROM USER_TRIGGERS;
/
--SELECT TRIGGER_NAME, TABLE_NAME, STATUS
--FROM USER_TRIGGERS WHERE TABLE_NAME='FIDE_CATEGORIA_TB';

