-------SUB PAQUETE DE FUCIONES 
create or replace package BODY FIDE_PROYECTO_FINAL_FN_PKG AS

-- FUNCION 1: Calcular el precio con IVA
FUNCTION FIDE_FACTURA_CALCULAR_PRECIO_IVA_FN(SUBTOTAL NUMBER, IMPUESTO NUMBER)
RETURN NUMBER IS 
BEGIN 
    RETURN SUBTOTAL * (1 + IMPUESTO);
END;

-- FUNCION 2: Verificar la fecha de caducidad
FUNCTION FIDE_PRODUCTO_VERIFICAR_FECHA_CADUCIDAD_FN(P_FECHA_VENCIMIENTO DATE)
RETURN VARCHAR2 IS
    V_ESTADO VARCHAR2(50);
BEGIN
    IF P_FECHA_VENCIMIENTO < SYSDATE THEN
        V_ESTADO := 'VENCIDO';
    ELSE
        V_ESTADO := 'VIGENTE';
    END IF;
    RETURN V_ESTADO;
END;

-- FUNCION 3: Calcular el total de una factura
FUNCTION FIDE_FACTURA_CALCULAR_TOTAL_FN(P_ID_FACTURA NUMBER) 
RETURN NUMBER IS 
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT SUM(PRECIO * CANTIDAD)
    INTO V_TOTAL
    FROM FIDE_FACTURA_DETALLE_TB
    WHERE ID_FACTURA_HEADER = P_ID_FACTURA;
    RETURN V_TOTAL;
END;

-- FUNCION 4: Verificar el stock de un producto
FUNCTION FIDE_INVENTARIO_VERIFICAR_STOCK_FN(P_ID_PRODUCTO NUMBER) 
RETURN NUMBER IS
    V_STOCK NUMBER := 0;
BEGIN
    SELECT SUM(CANTIDAD)
    INTO V_STOCK
    FROM FIDE_INVENTARIO_TB
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;
    RETURN V_STOCK;
END;

-- FUNCION 5: Verificar si un producto está en promoción
FUNCTION FIDE_PROMOCION_VERIFICAR_ESTADO_FN(P_ID_PRODUCTO NUMBER, P_FECHA_ACTUAL DATE DEFAULT SYSDATE)
RETURN VARCHAR2 IS
    V_PROMOCION_ACTIVA VARCHAR2(20);
BEGIN
    SELECT CASE 
        WHEN P_FECHA_ACTUAL BETWEEN FECHA_INICIO AND FECHA_FIN THEN 'En promoción'
        ELSE 'Sin promoción'
    END
    INTO V_PROMOCION_ACTIVA
    FROM FIDE_PROMOCION_TB
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;
    RETURN V_PROMOCION_ACTIVA;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Sin promoción';
END;

-----funcion 6  validar usuario 

FUNCTION FIDE_PERSONA_TB_VALIDAR_NOMBRE_USUARIO_FN(P_NOMBRE_USUARIO VARCHAR)
RETURN NUMBER IS
P_RESULTADO NUMBER;
BEGIN
    SELECT COUNT(*) INTO P_RESULTADO
    FROM FIDE_PERSONA_TB WHERE NOMBRE_USUARIO = P_NOMBRE_USUARIO 
    AND ID_ESTADO = 1;
    RETURN P_RESULTADO;
END;


END FIDE_PROYECTO_FINAL_FN_PKG;








---llamarlos 
--#1
CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_FN_PKG AS 
  FUNCTION FIDE_FACTURA_CALCULAR_PRECIO_IVA_FN return number;
END FIDE_PROYECTO_FINAL_FN_PKG;
/

--#2
CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_FN_PKG AS 
  FUNCTION FIDE_PRODUCTO_VERIFICAR_FECHA_CADUCIDAD_FN return VARCHAR2;
END FIDE_PROYECTO_FINAL_FN_PKG;
/

--#3
CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_FN_PKG AS 
  FUNCTION FIDE_FACTURA_CALCULAR_TOTAL_FN return varchar2;
END FIDE_PROYECTO_FINAL_FN_PKG;
/

--#4
CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_FN_PKG AS 
  FUNCTION FIDE_INVENTARIO_VERIFICAR_STOCK_FN return number;
END FIDE_PROYECTO_FINAL_FN_PKG;
/

--#5
CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_FN_PKG AS 
  FUNCTION FIDE_PROMOCION_VERIFICAR_ESTADO_FN return VARCHAR2;
END FIDE_PROYECTO_FINAL_FN_PKG;
/

--#6
CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_FN_PKG AS 
  FUNCTION FIDE_PERSONA_TB_VALIDAR_NOMBRE_USUARIO_FN return number;
END FIDE_PROYECTO_FINAL_FN_PKG;
/




----------------------------------------------------------------------
create or replace package  FIDE_PROYECTO_FINAL_FN_PKG AS

FUNCTION FIDE_FACTURA_CALCULAR_PRECIO_IVA_FN RETURN NUMBER;
FUNCTION FIDE_PRODUCTO_VERIFICAR_FECHA_CADUCIDAD_FN return varchar2;
FUNCTION FIDE_FACTURA_CALCULAR_TOTAL_FN return number;
FUNCTION FIDE_INVENTARIO_VERIFICAR_STOCK_FN return number;
FUNCTION FIDE_PROMOCION_VERIFICAR_ESTADO_FN return varchar2;
FUNCTION FIDE_PERSONA_TB_VALIDAR_NOMBRE_USUARIO_FN return number;

END FIDE_PROYECTO_FINAL_FN_PKG;














-------------------------------------------------------------------------------------------------------------------------------------
--llenar sub carpeta de SP
create or replace package BODY FIDE_PROYECTO_FINAL_SP_PKG AS


















END FIDE_PROYECTO_FINAL_SP_PKG;
