CREATE MATERIALIZED VIEW INFO_PRODUCTOS_PROVEEDOR_VM 
REFRESH COMPLETE ON DEMAND AS 
SELECT A.NOMBRE_PRODUCTO, A.DESCRIPCION, B.NOMBRE_PROVEEDOR
FROM FIDE_PRODUCTO_TB A, FIDE_PROVEEDOR_TB B
WHERE A.ID_PROVEEDOR=B.ID_PROVEEDOR;

--SELECT*FROM INFO_PRODUCTOS_PROVEEDOR_VM;

CREATE MATERIALIZED VIEW INFO_CANTIDAD_PRODUCTOS_SUCURSAL_VM 
REFRESH COMPLETE ON DEMAND AS 
SELECT A.NOMBRE_PRODUCTO,B.CANTIDAD,C.NOMBRE AS NOMBRE_SUCURSAL
FROM FIDE_PRODUCTO_TB A, FIDE_INVENTARIO_TB B , FIDE_SUCURSAL_TB C
WHERE A.ID_PRODUCTO=B.ID_PRODUCTO
AND B.ID_SUCURSAL=C.ID_SUCURSAL;

--SELECT*FROM INFO_CANTIDAD_PRODUCTOS_SUCURSAL_VM;

CREATE MATERIALIZED VIEW INFO_DEVOLUCION_PRODUCTO_COSTO_VM 
REFRESH COMPLETE ON DEMAND AS 
SELECT A.FECHA_DEVOLUCION,A.RAZON,B.NOMBRE_PRODUCTO,B.PRECIO_UNITARIO
FROM FIDE_DEVOLUCION_TB A, FIDE_PRODUCTO_TB B
WHERE A.ID_PRODUCTO=B.ID_PRODUCTO;

DECLARE
CURSOR DEVOLUCIO_CURSOR IS
SELECT 
FECHA_DEVOLUCION,
RAZON,
NOMBRE_PRODUCTO,
PRECIO_UNITARIO
FROM INFO_DEVOLUCION_PRODUCTO_COSTO_VM;

    V_FECHA_DEVOLUCION INFO_DEVOLUCION_PRODUCTO_COSTO_VM.FECHA_DEVOLUCION%TYPE;
    V_RAZON INFO_DEVOLUCION_PRODUCTO_COSTO_VM.RAZON%TYPE;
    V_NOMBRE_PRODUCTO INFO_DEVOLUCION_PRODUCTO_COSTO_VM.NOMBRE_PRODUCTO%TYPE;
    V_PRECIO_UNITARIO INFO_DEVOLUCION_PRODUCTO_COSTO_VM.PRECIO_UNITARIO%TYPE;
BEGIN
OPEN DEVOLUCIO_CURSOR;
LOOP
        
FETCH DEVOLUCIO_CURSOR INTO V_FECHA_DEVOLUCION, V_RAZON, V_NOMBRE_PRODUCTO, V_PRECIO_UNITARIO;
EXIT WHEN DEVOLUCIO_CURSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Fecha Devolución: ' || V_FECHA_DEVOLUCION || 
                             ' | Razón: ' || V_RAZON || 
                             ' | Producto: ' || V_NOMBRE_PRODUCTO || 
                             ' | Precio: ' || V_PRECIO_UNITARIO);
                             END LOOP;
    CLOSE DEVOLUCIO_CURSOR;
END;

--SELECT*FROM INFO_CANTIDAD_PRODUCTOS_SUCURSAL_VM;

CREATE MATERIALIZED VIEW INFO_HISTORIAL_DE_COMPRAS_VM 
REFRESH COMPLETE ON DEMAND AS 
SELECT A.ID_ANALISIS,A.TOTAL_VENTAS,A.FRECUENCIA,B.NOMBRE_PRODUCTO,C.NOMBRE,A.CREADO_POR,A.FECHA_CREACION
FROM FIDE_ANALISIS_VENTA_TB A, FIDE_PRODUCTO_TB B , FIDE_PERSONA_TB C
WHERE A.ID_PRODUCTO=B.ID_PRODUCTO
AND A.ID_PERSONA=A.ID_PERSONA;
-----------------------------------------------------------------------
CREATE MATERIALIZED VIEW INFO_LISTADO_DE_PEDIDOS_VM 
REFRESH COMPLETE ON DEMAND AS 
SELECT A.ID_PEDIDO,A.FECHA_CREACION AS FEHCA_PEDIDO,B.NOMBRE AS NOMBRE_TRABAJADOR,A.CREADO_POR,A.FECHA_CREACION
FROM FIDE_PEDIDO_TB A,FIDE_PERSONA_TB B
WHERE A.ID_PERSONA=B.ID_PERSONA;
------------------------------------------------------------------
CREATE MATERIALIZED VIEW INFO_PRODUCTOS_EN_SUCURSALES_VM 
REFRESH COMPLETE ON DEMAND AS 
SELECT A.CANTIDAD ,B.NOMBRE AS NOMBRE_SUCURSAL,C.NOMBRE_PRODUCTO
FROM FIDE_INVENTARIO_TB A,FIDE_SUCURSAL_TB B, FIDE_PRODUCTO_TB C
WHERE A.ID_SUCURSAL=B.ID_SUCURSAL
AND A.ID_PRODUCTO=C.ID_PRODUCTO;
------------------------------------------------------------------------
CREATE MATERIALIZED VIEW INFO_CANTIDAD_FACTURAS_SUCURSAL_VM 
REFRESH COMPLETE ON DEMAND AS 
SELECT B.NOMBRE AS NOMBRE_SUCURSAL,A.TOTAL_VENTAS,A.FECHA_CREACION
FROM FIDE_ANALISIS_VENTA_TB A, FIDE_SUCURSAL_TB B
WHERE A.ID_SUCURSAL=B.ID_SUCURSAL;
-------------------------------------------------------------------
CREATE MATERIALIZED VIEW INFO_PRODUCTOS_MAS_VENDIDOS_VM 
REFRESH COMPLETE ON DEMAND AS 
SELECT A.NOMBRE_PRODUCTO,B.CANTIDAD AS CANTIDAD_PRODUCTOS_VENDIDOS
FROM FIDE_PRODUCTO_TB A, FIDE_FACTURA_DETALLE_TB B
WHERE A.ID_FACTURA_DETALLE=B.ID_FACTURA_DETALLE;
------------------------------------------------------------
CREATE OR REPLACE VIEW INFO_DEVOLUCION_POR_MES_V
AS
SELECT TO_CHAR(FECHA_DEVOLUCION,'YYYY-MM')ANNO_MES,
COUNT(*) AS CANTIDAD_DEVOLUCIONES
FROM FIDE_DEVOLUCION_TB
GROUP BY 
TO_CHAR(FECHA_DEVOLUCION, 'YYYY-MM')
ORDER BY ANNO_MES;
---------------------------------------------------
CREATE MATERIALIZED VIEW INFO_VENTAS_DIARIAS_VM 
REFRESH COMPLETE ON DEMAND AS 
SELECT A.NOMBRE_PRODUCTO,B.FECHA_CREACION AS FEHCA_VENTA,B.TOTAL_VENTAS AS VENTAS_TOTALES
FROM FIDE_PRODUCTO_TB A, FIDE_ANALISIS_VENTA_TB B
WHERE A.ID_ANALISIS=B.ID_ANALISIS;

DROP MATERIALIZED VIEW  INFO_CANTIDAD_FACTURAS_SUCURSAL_VM ; 

DESCRIBE FIDE_DEVOLUCION_TB;
SELECT*FROM INFO_VENTAS_DIARIAS_VM ;




CREATE OR REPLACE VIEW FIDE_PROMOCIONES_ACTIVAS_V
AS
SELECT P.ID_PROMOCION,P.DESCRIPCION,P.FECHA_INICIO,
P.FECHA_FIN,P.DESCUENTO,PRO.ID_PRODUCTO,PRO.NOMBRE_PRODUCTO,PRO.PRECIO_UNITARIO,
PRO.PRECIO_UNITARIO - (PRO.PRECIO_UNITARIO * (P.DESCUENTO / 100)) PRECIO_FINAL
FROM FIDE_PROMOCION_TB P
INNER JOIN FIDE_PRODUCTO_TB PRO
ON P.ID_PRODUCTO = PRO.ID_PRODUCTO;

SELECT * FROM FIDE_PROMOCIONES_ACTIVAS_V;

CREATE OR REPLACE PROCEDURE FIDE_PROMOCION_TB_VER_PROMOCIONES_ACTIVAS_SP (
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
    SELECT 
        ID_PROMOCION, 
        DESCRIPCION, 
        FECHA_INICIO, 
        FECHA_FIN, 
        DESCUENTO, 
        ID_PRODUCTO, 
        NOMBRE_PRODUCTO, 
        PRECIO_UNITARIO,
        PRECIO_FINAL
    FROM FIDE_PROMOCIONES_ACTIVAS_V;
END FIDE_PROMOCION_TB_VER_PROMOCIONES_ACTIVAS_SP;
/

CREATE OR REPLACE VIEW FIDE_INFO_FACTURA_V AS
SELECT 
    H.ID_FACTURA_HEADER AS ID_FACTURA_HEADER,H.FECHA_CREACION,H.SUBTOTAL,
    H.IMPUESTO,H.TOTAL,H.TOTAL_LINEAS,M.NOMBRE AS NOMBRE_METODO_PAGO,
    PER.NOMBRE_USUARIO,S.NOMBRE AS NOMBRE_SUCURSAL,D.PRECIO,D.CANTIDAD,
    P.NOMBRE_PRODUCTO, H.ID_ESTADO
FROM FIDE_FACTURA_HEADER_TB H
INNER JOIN FIDE_FACTURA_DETALLE_TB D 
    ON H.ID_FACTURA_HEADER = D.ID_FACTURA_HEADER
INNER JOIN FIDE_PRODUCTO_TB P
    ON D.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN FIDE_PERSONA_TB PER
    ON H.ID_PERSONA = PER.ID_PERSONA
INNER JOIN FIDE_METODO_PAGO_TB M
    ON H.ID_METODO_PAGO = M.ID_METODO_PAGO
INNER JOIN FIDE_SUCURSAL_TB S
    ON H.ID_SUCURSAL = S.ID_SUCURSAL;


--INSERTS
-- Insertar datos en FIDE_PAIS_TB
INSERT INTO FIDE_PAIS_TB (NOMBRE) VALUES ('Costa Rica');

-- Insertar datos en FIDE_PROVINCIA_TB
INSERT INTO FIDE_PROVINCIA_TB (NOMBRE) VALUES ('San José');
INSERT INTO FIDE_PROVINCIA_TB (NOMBRE) VALUES ('Alajuela');
INSERT INTO FIDE_PROVINCIA_TB (NOMBRE) VALUES ('Cartago');
INSERT INTO FIDE_PROVINCIA_TB (NOMBRE) VALUES ('Heredia');
INSERT INTO FIDE_PROVINCIA_TB (NOMBRE) VALUES ('Guanacaste');
INSERT INTO FIDE_PROVINCIA_TB (NOMBRE) VALUES ('Puntarenas');
INSERT INTO FIDE_PROVINCIA_TB (NOMBRE) VALUES ('Limón');

-- Insertar datos en FIDE_CANTON_TB
-- San José
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('San José');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Escazú');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Desamparados');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Puriscal');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Tarrazú');

-- Alajuela
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Alajuela');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('San Ramón');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Grecia');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Atenas');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Poás');

-- Cartago
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Cartago');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Paraíso');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('La Unión');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Jiménez');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Turrialba');

-- Heredia
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Heredia');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Barva');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Santo Domingo');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('San Rafael');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('San Isidro');

-- Guanacaste
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Liberia');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Nicoya');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Santa Cruz');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Bagaces');
INSERT INTO FIDE_CANTON_TB (NOMBRE) VALUES ('Carrillo');

-- Insertar datos en FIDE_DISTRITO_TB
-- Distritos de San José
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Carmen');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Merced');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Hospital');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Mata Redonda');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Uruca');

-- Distritos de Alajuela
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Alajuela');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('San José');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Carrizal');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('San Antonio');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Guácima');

-- Distritos de Cartago
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Oriental');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Occidental');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Carmen');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('San Nicolás');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Aguacaliente');

-- Distritos de Heredia
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Heredia');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Mercedes');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('San Francisco');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Ulloa');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Varablanca');

-- Distritos de Liberia
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Liberia');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Cañas Dulces');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Mayorga');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Curubandé');
INSERT INTO FIDE_DISTRITO_TB (NOMBRE) VALUES ('Nacascolo');

INSERT INTO FIDE_METODO_PAGO_TB(NOMBRE, DESCRIPCION)VALUES
('TARJETA','AA');
